#cloud-config
packages:
  - docker.io
  - fail2ban

users:
  - name: valheim
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ${ssh_public_key}

write_files:
  - content: |
      net.ipv4.conf.default.rp_filter = 1
      net.ipv4.conf.all.rp_filter = 1
      net.ipv4.tcp_syncookies = 1
      net.ipv4.ip_forward = 0
      net.ipv4.conf.all.accept_redirects = 0
      net.ipv6.conf.all.accept_redirects = 0
      net.ipv4.conf.default.accept_redirects = 0
      net.ipv6.conf.default.accept_redirects = 0
      net.ipv4.conf.all.send_redirects = 0
      net.ipv4.conf.default.send_redirects = 0
      net.ipv4.conf.all.accept_source_route = 0
      net.ipv6.conf.all.accept_source_route = 0
      net.ipv4.conf.default.accept_source_route = 0
      net.ipv6.conf.default.accept_source_route = 0
      net.ipv4.conf.all.log_martians = 1
      net.ipv4.tcp_max_syn_backlog = 2048
      net.ipv4.tcp_synack_retries = 2
      net.ipv4.tcp_syn_retries = 5
      net.ipv4.icmp_ignore_bogus_error_responses = 1
      net.ipv4.icmp_echo_ignore_broadcasts = 1
      net.ipv4.icmp_echo_ignore_all = 1
      kernel.exec-shield = 1
      kernel.randomize_va_space = 1
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
      net.ipv4.conf.all.secure_redirects = 0
      net.ipv4.conf.default.secure_redirects = 0
      net.ipv6.conf.default.router_solicitations = 0
      net.ipv6.conf.default.accept_ra_rtr_pref = 0
      net.ipv6.conf.default.accept_ra_pinfo = 0
      net.ipv6.conf.default.accept_ra_defrtr = 0
      net.ipv6.conf.default.autoconf = 0
      net.ipv6.conf.default.dad_transmits = 0
      net.ipv6.conf.default.max_addresses = 1
      vm.panic_on_oom = 1
      kernel.panic = 10
    owner: root:root
    path: /etc/sysctl.d/valheim.conf
    permissions: 0644

  - content: |
      Port 22
      Protocol 2
      LogLevel VERBOSE
      PermitRootLogin no
      StrictModes yes
      RSAAuthentication yes
      IgnoreRhosts yes
      RhostsAuthentication no
      RhostsRSAAuthentication no
      PermitEmptyPasswords no
      PasswordAuthentication no
      ClientAliveInterval 300
      ClientAliveCountMax 0
      AllowTcpForwarding no
      X11Forwarding no
      UseDNS no
    owner: root:root
    path: /etc/ssh/sshd_config.d/valheim.conf
    permissions: 0644

  - content: |
      SERVER_NAME=${valheim_server_name}
      SERVER_PORT=2456
      WORLD_NAME=${valheim_world_name}
      SERVER_PASS=${valheim_server_password}
      SERVER_PUBLIC=false
      PERMITTEDLIST_IDS=${steam_ids_permitted}
      ADMINLIST_IDS=${steam_ids_admin}
    owner: root:root
    path: /etc/sysconfig/valheim.env
    permissions: 0644

  - content: |
      [Unit]
      Description=Valheim Server
      After=docker.service
      Requires=docker.service
      ConditionPathExists=/etc/sysconfig/valheim.env

      [Service]
      TimeoutStartSec=0
      ExecStartPre=-/usr/bin/docker stop valheim-server
      ExecStartPre=-/usr/bin/docker rm valheim-server
      ExecStart=/usr/bin/docker run \
        --name valheim-server \
        --pull=always \
        --rm \
        --cap-add=sys_nice \
        --stop-timeout 120 \
        -v /etc/valheim:/config:Z \
        -v /opt/valheim:/opt/valheim:Z \
        -p 2456-2457:2456-2457/udp \
        --env-file /etc/sysconfig/valheim.env \
        ghcr.io/lloesche/valheim-server
      ExecStop=/usr/bin/docker stop valheim-server
      Restart=always
      RestartSec=10s

      [Install]
      WantedBy=multi-user.target
    owner: root:root
    path: /usr/lib/systemd/system/valheim.service
    permissions: 0644

runcmd:
  - mkdir -p /etc/valheim /opt/valheim
  - chown -R valheim:valheim /etc/valheim /opt/valheim
  - timedatectl set-timezone Australia/Sydney
  - echo 'ENABLED="0"' >> /etc/default/irqbalance
  - passwd -l root
  - apt-get update
  - apt-get upgrade
  - apt-get autoremove
  - apt-get autoclean
  - sysctl -p
  - systemctl daemon-reload
  - systemctl restart sshd
  - systemctl enable docker.service valheim.service
  - systemctl start docker.service valheim.service